### ISSUE TITLE
Malformed onboarding.json entries

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/badges#14]
The `onboarding.json` contains several entries with `"pkgname": null` which causes issues like https://github.com/ropensci-org/rotemplate/issues/104

```
  {
    "pkgname": null,
    "submitted": "maelle",
    "iss_no": 24,
    "status": "reviewed",
    "version": "0.1",
    "stats_version": null
  },
```

**Comment by mpadge** [comment]
Onto it. I shifted the whole deploy from ruby to R yesterday. I saw those appear, but didn't know implications because there are no tests. Thanks for bug finding!

**Comment by mpadge** [comment]
@jeroen Those were all due to mal-formed review issues which I've now manually fixed. Please keep an eye out for any other issues that arise and let me know - the old script used some really error-prone regex-ing that the new version fixes, so other issues may still arise. I've re-deployed now, but will keep this issue open a day or two longer just in case. Thanks
