### ISSUE TITLE
`onboarded.json` showing 'pending' for completed reviews

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/badges#9]
For example `cffr` and `melt`: https://github.com/ropensci-org/badges/blob/gh-pages/json/onboarded.json

It seems that the corresponding badge images are actually correct:

 (cffr) https://github.com/ropensci-org/badges/blob/gh-pages/463_status.svg
 (melt) https://github.com/ropensci-org/badges/blob/gh-pages/550_status.svg

**Comment by mpadge** [comment]
Thanks @jeroen, i'm watching this repo now. Those glitches were because of rogue labels, mostly "topic:peer-reviewed". Scott had a grep in the ruby script for "review" labels that accidentally picked up those ones as pending. I've fixed the labels, and confirmed the "onboarded.json" is clean, but won't close until i've made the grep more robust.
